service: gapi-sequelize-serverless
provider:
  name: aws
  runtime: nodejs8.10
  stage: staging
  profile: default
  region: us-east-2

functions:
  auth:
    handler: dist/auth/main.handler
    events:
      - http:
          path: "/auth/{proxy+}"
          method: any
          cors: true
          integration: lambda-proxy
    memorySize: 128
    timeout: 10
  # user:
  #   handler: dist/user/main.handler
  #   events:
  #     - http:
  #         path: "/user/{proxy+}"
  #         method: any
  #         cors: true
  #         integration: lambda-proxy
  #   memorySize: 128
  #   timeout: 10

plugins:
  - serverless-offline
